# Generated by Django 5.0.6 on 2024-07-09 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customers_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_master',
            name='Custm_id',
        ),
        migrations.RemoveField(
            model_name='booking_master',
            name='table_id',
        ),
        migrations.RemoveField(
            model_name='booking_status',
            name='Bm_id',
        ),
        migrations.RemoveField(
            model_name='booking_status',
            name='Chef_id',
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='name')),
                ('Phone', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Persons', models.IntegerField()),
                ('Date', models.DateField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customers')),
            ],
        ),
        migrations.AlterField(
            model_name='payments',
            name='bm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.booking'),
        ),
        migrations.AlterField(
            model_name='suggestions',
            name='bm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.booking'),
        ),
        migrations.DeleteModel(
            name='Booking_child',
        ),
        migrations.DeleteModel(
            name='Booking_status',
        ),
        migrations.DeleteModel(
            name='Booking_master',
        ),
    ]
