# Generated by Django 5.0.6 on 2024-07-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_suggestions_bm_id_delete_payments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Name')),
                ('Phone', models.BigIntegerField(verbose_name='Phone')),
                ('Email', models.EmailField(max_length=254, verbose_name='Email')),
                ('Persons', models.IntegerField(verbose_name='Person')),
                ('Date', models.DateField(verbose_name='Date')),
            ],
        ),
    ]
