# Generated by Django 5.0.6 on 2024-07-24 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
