# Generated by Django 5.0.6 on 2024-09-24 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
