# Generated by Django 5.0.6 on 2024-10-23 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_cart_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
