# Generated by Django 5.0.6 on 2024-10-23 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Name')),
                ('Phone', models.BigIntegerField(verbose_name='Phone')),
                ('Email', models.EmailField(max_length=254, verbose_name='Email')),
                ('Persons', models.IntegerField(verbose_name='Person')),
                ('Date', models.DateField(verbose_name='Date')),
                ('Status', models.IntegerField(default=0, verbose_name='Status')),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customers')),
            ],
        ),
    ]
