# Generated by Django 5.0.6 on 2024-11-13 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
